-- MySQL Script generated by MySQL Workbench
-- Wed Jun 17 00:06:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema libreria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema libreria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `libreria` DEFAULT CHARACTER SET utf8 ;
USE `libreria` ;

-- -----------------------------------------------------
-- Table `libreria`.`Editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`Editorial` (
  `idEditorial` INT NOT NULL,
  `nomEditorial` VARCHAR(45) NULL,
  PRIMARY KEY (`idEditorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`Libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`Libros` (
  `idLibro` INT NOT NULL,
  `nomLibro` VARCHAR(45) NULL,
  `peso` VARCHAR(45) NULL,
  `publicación` DATE NULL,
  `precio` DOUBLE NULL,
  `estado` TINYINT NOT NULL,
  `Editorial_idEditorial` INT NOT NULL,
  PRIMARY KEY (`idLibro`, `Editorial_idEditorial`),
  INDEX `fk_Libros_Editorial1_idx` (`Editorial_idEditorial` ASC),
  CONSTRAINT `fk_Libros_Editorial1`
    FOREIGN KEY (`Editorial_idEditorial`)
    REFERENCES `libreria`.`Editorial` (`idEditorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`Categorias` (
  `idCategoria` INT NOT NULL,
  `nomCategoria` VARCHAR(45) NULL,
  `estado` TINYINT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`Autor` (
  `idAutor` INT NOT NULL,
  `nomAutor` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`Imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`Imagenes` (
  `idImagenes` INT NOT NULL,
  `nomImagen` VARCHAR(45) NULL,
  `urlImagen` VARCHAR(45) NULL,
  `estado` TINYINT NOT NULL,
  `Libros_idLibro` INT NOT NULL,
  PRIMARY KEY (`idImagenes`, `Libros_idLibro`),
  INDEX `fk_Imagenes_Libros1_idx` (`Libros_idLibro` ASC),
  CONSTRAINT `fk_Imagenes_Libros1`
    FOREIGN KEY (`Libros_idLibro`)
    REFERENCES `libreria`.`Libros` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`roles` (
  `idrole` INT NOT NULL,
  `nomrole` VARCHAR(45) NULL,
  PRIMARY KEY (`idrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`Usuarios` (
  `idUsuario` INT NOT NULL,
  `nonUsuario` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `estado` TINYINT NOT NULL,
  `roles_idrole` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `roles_idrole`),
  INDEX `fk_Usuarios_roles_idx` (`roles_idrole` ASC),
  CONSTRAINT `fk_Usuarios_roles`
    FOREIGN KEY (`roles_idrole`)
    REFERENCES `libreria`.`roles` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`Comentarios` (
  `idComentario` INT NOT NULL,
  `comentario` VARCHAR(45) NULL,
  `fechaComentario` VARCHAR(45) NULL,
  `valoracion` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `Libros_idLibro` INT NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idComentario`, `Libros_idLibro`, `Usuarios_idUsuario`),
  INDEX `fk_Comentarios_Libros1_idx` (`Libros_idLibro` ASC),
  INDEX `fk_Comentarios_Usuarios1_idx` (`Usuarios_idUsuario` ASC),
  CONSTRAINT `fk_Comentarios_Libros1`
    FOREIGN KEY (`Libros_idLibro`)
    REFERENCES `libreria`.`Libros` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `libreria`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`Categorias_has_Libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`Categorias_has_Libros` (
  `Categorias_idCategoria` INT NOT NULL,
  `Libros_idLibro` INT NOT NULL,
  PRIMARY KEY (`Categorias_idCategoria`, `Libros_idLibro`),
  INDEX `fk_Categorias_has_Libros_Libros1_idx` (`Libros_idLibro` ASC),
  INDEX `fk_Categorias_has_Libros_Categorias1_idx` (`Categorias_idCategoria` ASC),
  CONSTRAINT `fk_Categorias_has_Libros_Categorias1`
    FOREIGN KEY (`Categorias_idCategoria`)
    REFERENCES `libreria`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categorias_has_Libros_Libros1`
    FOREIGN KEY (`Libros_idLibro`)
    REFERENCES `libreria`.`Libros` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`Libros_has_Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`Libros_has_Autor` (
  `Libros_idLibro` INT NOT NULL,
  `Autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`Libros_idLibro`, `Autor_idAutor`),
  INDEX `fk_Libros_has_Autor_Autor1_idx` (`Autor_idAutor` ASC),
  INDEX `fk_Libros_has_Autor_Libros1_idx` (`Libros_idLibro` ASC),
  CONSTRAINT `fk_Libros_has_Autor_Libros1`
    FOREIGN KEY (`Libros_idLibro`)
    REFERENCES `libreria`.`Libros` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libros_has_Autor_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `libreria`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
